# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Quentin Bouniot
author:
  name: Quentin Bouniot
  email: quentin[dot]bouniot[at]cea[dot]fr
description: Welcome to my blog and personal page !
github_username: qbouniot
lang: "en"

show_excerpts: false
baseurl: "/"

# Email and twitter are optional:
email: quentin[dot]bouniot[at]cea[dot]fr
twitter_username: QBouniot

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: QBouniot
    github:  qbouniot

# Set this to true to get LaTeX math equation support
use_math: True

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
# theme: minima
skins: classic
# remote_theme: niklasbuschmann/contrast@v2.8
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-seo-tag
  # - jekyll-remote-theme

paginate: 5

header_pages:
  - publications.md

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

github: [metadata]